src/commands/rover/WhoisCommand.js

Allow users to find out who someone is verified as

Add !whois command

---

src/DiscordServer.js

Short sighted attempt at fixing #30, #32, #33 
Seeing as the affected users have always just entered the server, preventing the caching of the users might help.

Removed user caching

---

README.md

In accordance with [Discord.js](https://github.com/hydrabolt/discord.js) requirements.

Change required Node.js version to 8.0.0

---

src/DiscordServer.js

Updating group-checking to use the latest Roblox web endpoint

---

src/commands/rover/WhoisCommand.js

Whois URL encoding

---

README.md
src/commands/rover/SupportCommand.js

Update discord invite link

---

src/commands/rover/NicknameFormatCommand.js

NicknameFormat setting return to default if argument is empty

---

README.md

The README seems a bit out of date.

Update README.md to show 500K+ verified users

---

src/commands/rover/WhoisCommand.js

Don't just silently fail, actually return that an error happened

Acknowledge error while whois'ing

---

src/commands/rover/SupportCommand.js

Some people might not want the discord link posted in their server. Some moderation bots might also delete the link automatically upon it being posted.

DM RoVer discord instead of posting it publicly

---

src/commands/rover/SupportCommand.js

Fix mistake with assuming command was able to be used in DMs

---

src/VirtualGroups.js

Detect Staff regardless of Primary Group

---

src/Util.js
src/index.js

Just like the users count changes "1,100,000" to "1.1M", the total servers count changes "44600" to "44.6K"

Simplify the number of servers being watched

---

src/VirtualGroups.js

Handle DevForum suspensions

---

src/DiscordBot.js
src/commands/rover/InviteCommand.js
src/commands/rover/SupportCommand.js

Get rid of pointless errors to console

---

src/DiscordServer.js
src/commands/rover/AnnounceChannelCommand.js
src/commands/rover/BindGroupCommand.js
src/commands/rover/CreateGroupRanks.js
src/commands/rover/JoinMessageCommand.js
src/commands/rover/NicknameCommand.js
src/commands/rover/NicknameFormatCommand.js
src/commands/rover/NicknameGroupCommand.js
src/commands/rover/NotVerifiedRoleCommand.js
src/commands/rover/UnbindAllGroupCommand.js
src/commands/rover/UnbindGroupCommand.js
src/commands/rover/VerifiedRoleCommand.js
src/commands/rover/VerifyChannelCommand.js
src/commands/rover/WelcomeMessageCommand.js

Literal 300iq pull request that took me many years of research and help from multiple computer science majors

Remove setting file corruption feature

---

README.md

Literally the only type of contribution I make to this project tbh

Update README.md with updated user count

---

README.md
src/commands/rover/WhoisCommand.js

Fix whois builders club + add premium & lifetime support

---

README.md
src/DiscordMember.js
src/commands/rover/BindGroupCommand.js
src/commands/rover/UpdateCommand.js
src/commands/rover/VerifyCommand.js

@evaera no throttling for patreon users?

Friendly error messages + verification throttling

---

src/VirtualGroups.js

Fix outdated virtual groups

---

README.md

Document maxServerBindings

---

package-lock.json
package.json
src/DiscordBot.js
src/DiscordMember.js
src/DiscordServer.js
src/commands/rover/CreateGroupRanks.js
src/commands/rover/CreateVerifyChannelCommand.js

Tested:
- verify
- update
- announcechannel
- createverifychannels
- whois
- Group bind functionality
- verifiedrole
- unverifiedrole
- rlookup
- bindings

Migrate to Discord.js v12

---

src/DiscordBot.js

Fixes the issue of the bot pinging everyone when the update command is ran as !update v

Disable everyone mention

---

src/commands/rover/UpdateCommand.js

Fix for Discord Intent based mass updating break.

---

src/DiscordMember.js
src/DiscordServer.js
src/VirtualGroups.js
src/commands/rover/CreateGroupRanks.js
src/commands/rover/WhoisCommand.js

These endpoints were removed/are slated for removal shortly: https://devforum.roblox.com/t/official-list-of-deprecated-web-endpoints/62889/37?u=frostedplasma13
I updated the endpoints, and did a little bit of testing. I think I ironed out any bugs, but I am willing to bet I likely missed something. I noticed there was another similar PR trying to fix this, however there are issues that were not solved that I made sure to.

Update from deprecated endpoints

---

src/commands/rover/ReverseLookupCommand.js

Allow users with rover reverse lookup role to perform reverse lookups

---

src/DiscordMember.js

Found a stray remaining old endpoint in discordmember

Fix final possibly-soon-to-be deprecated endpoint

---

README.md
src/VirtualGroups.js
src/commands/rover/WhoisCommand.js

The premium virtualgroup and whois command now use the premiumfeatures api, the `cookie` property is also added to the readme and `client.json` as the new endpoint requires authentication.

Fix premium check

---

src/Accolades.json
src/commands/rover/RestartCommand.js

As per Eryn's request, there is now a restart command for Helper+

Add restart command

---

src/Accolades.json

Add Rythian as support staff

---

src/commands/rover/UnverifyCommand.js

This resolves #327 which will send an invite link to the support server telling them to contact a moderator or above (which is who can unverify someone)

Unverify command

---

src/DiscordServer.js

Complete's Eryn's request for a better welcome message.

---

src/commands/rover/RestartCommand.js

- `shardIDForGuildID()` is a static method, so it needs to be called directly on the class constructor
- Defined the guildID parameter as `args.server` instead of `msg.guild.id`

fix restart command

---

src/DiscordMember.js
src/Util.js

Set displayname to username if displayname is undefined

---

index.md

Resolves https://github.com/evaera/RoVer/issues/351

Adds smartname and displayname to nickname formats

---

src/commands/rover/NicknameFormatCommand.js
src/commands/rover/WelcomeMessageCommand.js

Adds the %SMARTNAME% and %DISPLAYNAME% format options to !nicknameformat and !welcomemessage

Add smartname and displayname to commands

---

src/commands/rover/UpdateCommand.js

When no argument or the the user's own mention is passed, they will update themselves instead of being told they don't have permission.

Allow users to update self with update command

---

src/commands/rover/UnverifyCommand.js

Self unverification is possible now so telling people to join the support server is pointless.

Add unverification link to unverify command

---

src/commands/rover/UpdateCommand.js

Remove the bulk update error report functionality due to rate limiting giving false positives and the general lack of necessity

Remove bulk update error list
