evaera/RoVer

- src/commands/rover/HelpCommand.js
- src/commands/rover/WhoisCommand.js
Fix 'invalid form body content' error when trying to use the help command.
> Fix help command not working

- src/index.js
Added support for millions, billions, and trillions to the user count.
Insignificant display change, but it was starting to bother me as it wasn't fixed. Previously, RoVer would display "Listening to 1043.4K users" as millions were not supported. Now, it displays "Listening to 1.0M users". Billions and trillions were also added, and although it's excessive, it's better safe than sorry.
> Added millions support to user count

- src/VirtualGroups.js
The addition of two more virtual groups, Community Sage and Post Approval teams from the Developer Forums.
Users in these groups used to come under the Top Contributor VirtualGroup but due to the recent changes in structure, they were made separate to open up Top Contributor to public.
> Additional VirtualGroups

- src/commands/rover/BindGroupCommand.js
- src/commands/rover/NotVerifiedRoleCommand.js
- src/commands/rover/VerifiedRoleCommand.js
Confusing error message would say that RoVer didn't have perms to add/remove roles to the user when @everyone or @here was bound.
> Remove ability to bind @everyone/@here

- src/DiscordServer.js
- src/commands/rover/BindingsCommand.js
if we don't get any role cache complaints anymore, then it's safe to re-enable role cleanup again
> Possibly fix role cache bug

- index.md
The Virtual Groups section of the docs did not include all VirtualGroups within the bot.
> Update documentation (virtual groups)

- src/VirtualGroups.js
Added the new name for the full member rank of the Developer Forums as of February 2020.
**This does not rename `DevForumMember` despite the `New Member` rank being renamed `Member` due to compatibility issues.**
> Added 'DevForumRegular' VirtualGroup

- src/VirtualGroups.js
This pull requests adds a new VirtualGroup, `DevForumVisitor`, which gives a role when the user has a DevForum account but is not a Member+.
I also changed `getDevForumProfile()` to use another endpoint on the DevForum that allows to retrieve the data via the user id. This fixes a lot of problems with people changing their name and losing their roles and not knowing how to get them back or what the problem is.
> New VirtualGroup and changes to getDevForumProfile

- src/DiscordBot.js
RoVer should not automatically verify members on join if the server has a set verification level of high or very high, if it's medium then compare the member's joinedTimestamp and user.createdTimestamp, and autoverify if the account was created more than 5 minutes ago.
> Check server's verification level and act accordingly

- src/commands/rover/WhoisCommand.js
Embed data read the pastName instead of pastNames variable, which was undefined. Whois command did not work as such.
> Mistyped variable causing whois command to break

- src/commands/rover/WhoisCommand.js
Roblox appears to have blocked RoVer from downloading profile pages entirely, as of now we should start fetching the data from their api endpoints.
> Use api endpoints instead of downloading profile page

- src/DiscordBot.js
- src/commands/rover/BindGroupCommand.js
- src/commands/rover/JoinMessageCommand.js
- src/commands/rover/NotVerifiedRoleCommand.js
- src/commands/rover/VerifiedRoleCommand.js
Adds:
- Checks to see if a given role is above RoVer when binding and cancels the bind until RoVer is placed above that role.
- This includes Verifiedrole and Unverifiedrole
- Additional help information for Patrons using RoVer Plus in their server, letting them know to try <prefix>transferplus
- Additional help information for `joindm` stating that disabling it also turns of automatic verification on joining.
Resolves #298
> Adding automatic help and diagnostics

- src/commands/Command.js
- src/commands/rover/BindGroupCommand.js
- src/commands/rover/NotVerifiedRoleCommand.js
- src/commands/rover/VerifiedRoleCommand.js
Currently we've been seeing the verifiedrole command failing in some servers when .me is null, the notverifiedrole command was fixed as well in case that comes up.
> Fetch bot member in guild when .me is null

- src/commands/rover/WhoisCommand.js
Whois command should no longer error if the user doesn't have a devforum profile
> Fix bad check

- src/index.js
Just added the cookie field into the bottom of the file in the client.json documentation section to keep it update to date with the website, since someone else forgot to.🥴
> Update index.js Client.json documentation

- src/commands/rover/RestartCommand.js
The current version of the restart command only allows for restarting the current shard, this version will allow supplying a server id, which will be used to find the correct shard and restart it.
> Allow remote restarting of shard

- src/commands/rover/UnverifyCommand.js
- Fix UnverifyCommand.js not having a command description definition (crashes on run without it)
- Add Code's request to clarify that you don't need to unverify to reverify.
> Clarify UnverifyCommand

- src/DiscordBot.js
Previously, one could bypass guild security by going to verify.eryn.io and reverifying, this pr should update the behavior to match the behavior currently exhibited when a member joins a server
> Prevent server members from bypassing guild security settings

- src/DiscordMember.js
As of now verification is stopped entirely if the request to `users.roblox.com/v1/users/:id` fails, which has been causing plenty of issues for weeks now.
Instead we should continue and use the username the registry stores, which should be good enough since Roblox redirects old usernames. A warning was added to the bottom of the final status if we were ratelimited.
> Edit message to warn user if users api request fails

- src/DiscordBot.js
- src/GlobalCache.js
- src/index.js
A redo of #324 since the commit history got incredibly polluted.
Essentially the blocklist information will be fetched before any of the shards are spawned and placed into the GlobalCache via a special method that doesn't require a shard object to be passed, where it will be read from by each shard.
> Cache blocklisted users on start instead of fetching once for each shard (take 2)

- src/DiscordBot.js
This will allow certain commands like `help` to work in dms again. I also removed `disabledEvents` and `apiRequestMethod` as these are legacy client options and no longer exist.
> Add direct messages intent
